version: 1.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu2004
branches:
  only:
  - dev
configuration:
  - Debug
  - Release
platform: x64
environment:
  matrix:
  - BUILDER: MSBuilder
    HOST_OR_DOCKER: host
  - BUILDER: CMake
    HOST_OR_DOCKER: host
  - BUILDER: CMake
    HOST_OR_DOCKER: docker

matrix:
  fast_finish: true
  exclude:
    - image: Visual Studio 2019
      HOST_OR_DOCKER: docker
    - image: Ubuntu2004
      BUILDER: MSBuilder

init:
  - appveyor version

for:

  - matrix:
      only:
      - image: Visual Studio 2019
        BUILDER: MSBuilder

    install:
    - pwsh: |
            # installation of prerequisites: gtest
            nuget restore mssln -PackagesDirectory ../external/packages
            # cleaning, without which the build will not work
            rm -r samples01/test/mssln/obj

    build_script:
    - pwsh: msbuild "mssln/samples__leetcode_com.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    test_script:
    - pwsh: |
            [string]$target = "./mssln/$env:PLATFORM/$env:CONFIGURATION/samples01-test.exe"
            Start-Process -NoNewWindow -FilePath "$target" -ArgumentList '--gtest_color=yes'

  - matrix:
      only:
      - image: Visual Studio 2019
        BUILDER: CMake

    install:
    - pwsh: |
            pwsh --version
            # installation of prerequisites: gtest
            nuget install Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn -Version 1.8.1.5 -OutputDirectory ../external/packages

    build_script:
    - pwsh: pwsh -NonInteractive samples01/scripts/build-Microsoft.ps1 $env:CONFIGURATION
    test_script:
    - pwsh: pwsh -NonInteractive samples01/scripts/test-Microsoft.ps1 $env:CONFIGURATION

  - matrix:
      only:
      - image: Ubuntu2004
        HOST_OR_DOCKER: host

    install:
    - sh: |
          # installation of prerequisites: gtest
          sudo apt -y update
          sudo apt -y install libgtest-dev \
            && sudo mkdir -p /usr/src/gtest/build \
            && pushd /usr/src/gtest/build \
            && sudo cmake --build ..
          popd
          sudo rm -rf /usr/src/googletest
          sudo rm /usr/src/gtest
    build_script:
    - sh: bash samples01/scripts/build-Linux.sh $CONFIGURATION
    test_script:
    - sh: bash samples01/scripts/test-Linux.sh $CONFIGURATION

  - matrix:
      only:
      - image: Ubuntu2004
        HOST_OR_DOCKER: docker
    build_script:
    - sh: bash samples01/scripts/build-Linux.sh $CONFIGURATION
